USE COP4331;

INSERT INTO USERS (FirstName, LastName, Login, Password) VALUES ('Rick', 'Leinecker', 'RickL', 'COP4331');
INSERT INTO USERS (FirstName, LastName, Login, Password) VALUES ('Sam', 'Hill', 'SamH', 'Test');
INSERT INTO USERS (FirstName, LastName, Login, Password) VALUES ('Rick', 'Leinecker', 'RickL', '5832a71366768098cceb7095efb774f2');
INSERT INTO USERS (FirstName, LastName, Login, Password) VALUES ('Sam', 'Hill', 'SamH', '0cbc6611f5540bd0809a388dc95a615b');

INSERT INTO COLORS (ColorName, UserID) VALUES ('Blue', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('White', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Black', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Gray', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Magenta', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Yellow', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Cyan', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Salmon', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Chartreuse', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Lime', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Blue', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Gray', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Red', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Green', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Chiffon', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Fuscia', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Brown', 1);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Beige', 1);

INSERT INTO COLORS (ColorName, UserID) VALUES ('Blue', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('White', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Black', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Gray', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Magenta', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Yellow', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Cyan', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Salmon', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Chartreuse', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Lime', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Blue', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Gray', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Red', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Light Green', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Chiffon', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Fuscia', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Brown', 3);
INSERT INTO COLORS (ColorName, UserID) VALUES ('Beige', 3);

